2019-04-10T09:55:05.5473028+03:00;VSTestExecutionThread;Info;SpecFlow+Runner execution started
2019-04-10T09:55:05.5473028+03:00;VSTestExecutionThread;Info;SpecFlow+Runner 3.0.255 in Framework clr40 in x86 mode execution started
2019-04-10T09:55:05.5473028+03:00;VSTestExecutionThread;Info;TestAdapter Location: C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\TechTalk.SpecRun.VisualStudio.TestAdapter.dll
2019-04-10T09:55:05.7581822+03:00;VSTestExecutionThread;Info;SpecRun: running tests in C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\Tests.dll
2019-04-10T09:55:05.7581822+03:00;VSTestExecutionThread;Info;Output folder configured to "C:\Users\niga3\source\repos\End-To-End-Testing\TestResults" (default)
2019-04-10T09:55:05.7581822+03:00;VSTestExecutionThread;Info;Profile: Tests
2019-04-10T09:55:05.7941715+03:00;VSTestExecutionThread;Info;Log file path: C:\Users\niga3\source\repos\End-To-End-Testing\TestResults\Tests_Tests_2019-04-10T095505.log
2019-04-10T09:55:05.8081526+03:00;VSTestExecutionThread;Info;SpecFlow+Runner Evaluation Mode: Please purchase at http://www.specflow.org/plus to remove test execution delay.
2019-04-10T09:55:05.8171484+03:00;Thread#13;Info;Checking license
2019-04-10T09:55:05.8971010+03:00;Thread#13;Info;Evaluation mode: test execution starts in 10 seconds... (this delay is removed in the registered version)
2019-04-10T09:55:15.8982772+03:00;Thread#13;Info;Evaluation delay finished.
2019-04-10T09:55:15.9052719+03:00;Thread#13;Info;License check completed
2019-04-10T09:55:15.9052719+03:00;Thread#13;Info;starting test run
2019-04-10T09:55:15.9182654+03:00;Thread#13;Info;Discovering target: Default
2019-04-10T09:55:15.9192640+03:00;Thread#13;Info;Discovering tests from assembly: C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\Tests.dll
2019-04-10T09:55:16.4199758+03:00:Appdomain Disposed
2019-04-10T09:55:16.4209755+03:00;Thread#13;Info;Discovered tests from assembly: C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\Tests.dll
2019-04-10T09:55:16.4209755+03:00:Test Suite Dump
2019-04-10T09:55:16.4229749+03:00:#0: Tests/Tests - 
2019-04-10T09:55:16.4229749+03:00:#1: Default - 
2019-04-10T09:55:16.4229749+03:00:#2: Tests - 
2019-04-10T09:55:16.4229749+03:00:#7: PurchaseFlows - 
2019-04-10T09:55:16.4609535+03:00:#10: Clicking on "See basket" takes the user to basket page - TestAssembly:Tests/Feature:PurchaseFlows/Scenario:Clicking+on+%22See+basket%22+takes+the+user+to+basket+page
2019-04-10T09:55:16.4609535+03:00:End: Test Suite Dump
2019-04-10T09:55:16.4979322+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T09:55:16.5039282+03:00:Thread#:Scheduler: testitem #10 from normal test queue 
2019-04-10T09:55:16.5049279+03:00:Thread#0:Scheduler: considering testitem #10 for thread 0
2019-04-10T09:55:16.5129236+03:00:Thread#0:TestItem#10:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T09:55:16.5129236+03:00:Thread#0:TestItem#10:runsOnOneOtherThreadSpecific:False
2019-04-10T09:55:16.5129236+03:00:Thread#0:TestItem#10:runsOnOneOtherThreadUnspecific:False
2019-04-10T09:55:16.5129236+03:00:Thread#0:Scheduler: using testitem #10 for thread 0
2019-04-10T09:55:16.5149220+03:00:Thread#0:Scheduler: Test #10 is scheduled for thread
2019-04-10T09:55:16.5169223+03:00:Thread#0:Scheduler: with testItemExecutionIndex 0
2019-04-10T09:55:16.5249181+03:00:Thread #0: creating new test thread executor for Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
2019-04-10T09:55:16.5419082+03:00:Thread #0: Creating test assembly executor for execution model AppDomain
2019-04-10T09:55:16.5439093+03:00:Thread #0: Creating test assembly executor for execution model AppDomain
2019-04-10T09:55:16.5439093+03:00:using TechTalk.SpecRun.Framework.Execution.InProcess.InProcAppDomainTestAssemblyExecutorHost to execute tests
2019-04-10T09:55:16.6198615+03:00:Thread#0: Test #10/0 is started on thread #0
2019-04-10T09:55:16.7887645+03:00:Thread#0:T:-> Loading plugin C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\SpecRun.Runtime.SpecFlowPlugin.dll
2019-04-10T09:55:16.7937616+03:00:Thread#0:T:-> Using default config
2019-04-10T09:55:16.8787126+03:00:Thread#0:B:Given The user added a product to basket
2019-04-10T09:55:27.0469643+03:00:Thread#0:T:done: PurchaseFlowsSteps.GivenTheUserAddedAProductToBasket() (10.0s)
2019-04-10T09:55:27.0479636+03:00:Thread#0:B:When The user clicks on see basket button
2019-04-10T09:55:29.2203290+03:00:Thread#0:T:error: Exception has been thrown by the target of an invocation.
2019-04-10T09:55:29.2203290+03:00:Thread#0:B:Then The user is redirected to basket page
2019-04-10T09:55:29.2203290+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T09:55:29.2722987+03:00:Thread#0:TestItem#10:Scheduler: reschedule tests for testitem #10
2019-04-10T09:55:29.2733028+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T09:55:29.2733028+03:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #10
2019-04-10T09:55:29.2733028+03:00:Thread#0:Scheduler: considering testitem #10 for thread 0
2019-04-10T09:55:29.2733028+03:00:Thread#0:TestItem#10:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T09:55:29.2733028+03:00:Thread#0:TestItem#10:runsOnOneOtherThreadSpecific:False
2019-04-10T09:55:29.2733028+03:00:Thread#0:TestItem#10:runsOnOneOtherThreadUnspecific:False
2019-04-10T09:55:29.2742984+03:00:Thread#0:Scheduler: using testitem #10 for thread 0
2019-04-10T09:55:29.2742984+03:00:Thread#0:Scheduler: Test #10 is scheduled for thread
2019-04-10T09:55:29.2742984+03:00:Thread#0:Scheduler: with testItemExecutionIndex 1
2019-04-10T09:55:29.7180438+03:00:Thread#0: Test #10/0 is finished on thread #0 as Failed within 13.0981823 seconds
2019-04-10T09:55:29.7210414+03:00:Thread#0: Test #10/1 is started on thread #0
2019-04-10T09:55:29.7210414+03:00:Thread#0:B:Given The user added a product to basket
2019-04-10T09:55:33.7409146+03:00:Thread#0:T:error: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:60346
2019-04-10T09:55:33.7409146+03:00:Thread#0:T:   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2019-04-10T09:55:33.7409146+03:00:Thread#0:T:   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
2019-04-10T09:55:33.7409146+03:00:Thread#0:T:   --- End of inner exception stack trace ---
2019-04-10T09:55:33.7409146+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
2019-04-10T09:55:33.7419129+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream()
2019-04-10T09:55:33.7419129+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-04-10T09:55:33.7419129+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2019-04-10T09:55:33.7419129+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2019-04-10T09:55:33.7419129+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-04-10T09:55:33.7419129+03:00:Thread#0:B:When The user clicks on see basket button
2019-04-10T09:55:33.7419129+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T09:55:33.7419129+03:00:Thread#0:B:Then The user is redirected to basket page
2019-04-10T09:55:33.7429167+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T09:55:33.7439113+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T09:55:33.7439113+03:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #10
2019-04-10T09:55:33.7439113+03:00:Thread#0:Scheduler: considering testitem #10 for thread 0
2019-04-10T09:55:33.7439113+03:00:Thread#0:TestItem#10:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T09:55:33.7439113+03:00:Thread#0:TestItem#10:runsOnOneOtherThreadSpecific:False
2019-04-10T09:55:33.7439113+03:00:Thread#0:TestItem#10:runsOnOneOtherThreadUnspecific:False
2019-04-10T09:55:33.7439113+03:00:Thread#0:Scheduler: using testitem #10 for thread 0
2019-04-10T09:55:33.7439113+03:00:Thread#0:Scheduler: Test #10 is scheduled for thread
2019-04-10T09:55:33.7439113+03:00:Thread#0:Scheduler: with testItemExecutionIndex 2
2019-04-10T09:55:35.7535253+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:60346/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T09:55:35.7565247+03:00:Thread#0: Test #10/1 is finished on thread #0 as Failed within 6.0354833 seconds
2019-04-10T09:55:35.7575247+03:00:Thread#0: Test #10/2 is started on thread #0
2019-04-10T09:55:35.7575247+03:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-04-10T09:55:35.7575247+03:00:Thread#0:B:Given The user added a product to basket
2019-04-10T09:55:37.7653692+03:00:Thread#0:T:error: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:60346
2019-04-10T09:55:37.7663685+03:00:Thread#0:T:   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2019-04-10T09:55:37.7663685+03:00:Thread#0:T:   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
2019-04-10T09:55:37.7663685+03:00:Thread#0:T:   --- End of inner exception stack trace ---
2019-04-10T09:55:37.7663685+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
2019-04-10T09:55:37.7663685+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream()
2019-04-10T09:55:37.7663685+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-04-10T09:55:37.7663685+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2019-04-10T09:55:37.7663685+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2019-04-10T09:55:37.7663685+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-04-10T09:55:37.7673679+03:00:Thread#0:B:When The user clicks on see basket button
2019-04-10T09:55:37.7673679+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T09:55:37.7673679+03:00:Thread#0:B:Then The user is redirected to basket page
2019-04-10T09:55:37.7673679+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T09:55:37.7673679+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T09:55:37.7673679+03:00:Thread#:Scheduler: at the end of normal test queue
2019-04-10T09:55:37.7673679+03:00:Thread#0:Scheduler: enumerator for thread is at end
2019-04-10T09:55:37.7673679+03:00:Thread#0:Scheduler: No more tests for thread
2019-04-10T09:55:39.7742117+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:60346/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T09:55:39.7782101+03:00:Thread#0: Test #10/2 is finished on thread #0 as Failed within 4.0206854 seconds
2019-04-10T09:55:39.8001976+03:00:Appdomain Disposed
2019-04-10T09:55:39.8011969+03:00:Trying to cancel thread
2019-04-10T09:55:39.8011969+03:00:Thread cancelled
2019-04-10T09:55:39.8121904+03:00:Thread#-1:Scheduler: get next test for thread -1
2019-04-10T09:55:39.8121904+03:00:Thread#:Scheduler: at the end of normal test queue
2019-04-10T09:55:39.8121904+03:00:Thread#-1:Scheduler: enumerator for thread is at end
2019-04-10T09:55:39.8181881+03:00;Thread#13;Info;test run finished
2019-04-10T09:55:39.8181881+03:00;Thread#13;Info;publishing test results
2019-04-10T09:55:39.8511670+03:00;Thread#13;Info;test results published
2019-04-10T09:55:39.8511670+03:00;Thread#13;Info;generating reports
2019-04-10T09:55:40.0720418+03:00;Thread#13;Info;Starting external report generation process
2019-04-10T09:55:42.8824236+03:00;Thread#13;Info;Successfully generated reports.
2019-04-10T09:55:42.8844226+03:00;Thread#13;Info;Successfully generated reports
2019-04-10T09:55:42.8974206+03:00:Total: 1 (test executions: 3)
2019-04-10T09:55:42.9004128+03:00:Succeeded: 0
2019-04-10T09:55:42.9014121+03:00:Ignored: 0
2019-04-10T09:55:42.9014121+03:00:Pending: 0
2019-04-10T09:55:42.9014121+03:00:Skipped: 0
2019-04-10T09:55:42.9024114+03:00:Failed: 1
2019-04-10T09:55:42.9214020+03:00;VSTestExecutionThread;Info;Adding attachments to VSTest
2019-04-10T09:55:42.9214020+03:00;VSTestExecutionThread;Info;adding Test Execution Report 'C:\Users\niga3\source\repos\End-To-End-Testing\TestResults\TestRunReport.html'
========== End of log file ==========
